### PR TITLE
Fixed #444

### LINKED ISSUE #444: cardinal directions aren't working, contrary to the docs.
### Describe

Mods: ONLY CC:Tweaked and Advanced Peripherals.

The inventory manager does not currently allow cardinal directions. (even though supposedly it should? according to the docs at least)

Please fix.

example script:
`manager = peripheral.find("inventoryManager")
manager.addItemToPlayer("UP", 50, -1)`

Do correct me if I am doing something wrong here, but yeah it appears to not work.
This also means that the example script on the docs won't work. 
ALSO unrelated but the docs have the NBT version of the example in the non-nbt area and the non-nbt version in the nbt area.

### Steps to reproduce

1. get your CC setup. (put an inventory manager and such.)
2. Put a chest on top of the inventory manager,
3. put something in it
4. call `manager.addItemToPlayer("UP", 4, -1)`
5. It won't work because apparently the cardinal directions aren't enabled contrary to the docs.

### Multiplayer?

No

### Version

1.19.2-0.7.27r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Forge 43.2.8, Minecraft 1.19.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by zyxkad**
Updated `getDirection` in `CoordUtil.java` to fix #444

`Direction.byName` only accept lower case direction, so we need covert the direction as lower case first.

### CODE REVIEW

File: src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java [hunk 1]
```diff
@@ -48,31 +48,37 @@ public static boolean isInRange(@NotNull BlockPos blockPos, @NotNull Player play
...
     }
 
-    public static Direction getDirection(FrontAndTop orientation, String computerSide) throws LuaException {
-        if (Direction.byName(computerSide) != null) return Direction.byName(computerSide);
+    public static Direction getDirection(FrontAndTop orientation, final String computerSide) throws LuaException {
+        if (computerSide == null) {
+            throw new LuaException("null is not a valid side");
+        }
+
+        final String side = computerSide.toLowerCase();
```
Comment (SirEndii) [inline src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java]: Is there a particular reason you did this?
re-asigning the var would be enough and would remove one unnecessary var

**Comment by SirEndii** [comment]
I'll look into your PRs in the next week if I get the time

File: src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java (hunk 1 above)
Comment (zyxkad) [reply src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java]: > re-asigning the var would be enough and would remove one unnecessary var

I would like to throw the origin side that passed in when the side is not exists, but seems you already make them upperCase Idk why

```java
    // Line 134 at de.srendi.advancedperipherals.lib.peripherals.BasePeripheral
    protected Direction validateSide(String direction) throws LuaException {
        String dir = direction.toUpperCase(Locale.ROOT);

        return CoordUtil.getDirection(owner.getOrientation(), dir);
    }
```

**Comment by zyxkad** [comment]
> I'll look into your PRs in the next week if I get the time

Idk if you need I merge my prs and let you check easier? :)

File: src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java (hunk 1 above)
Comment (zyxkad) [reply src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java]: I removed line 135, if you think the exception should be case insensitive or always be uppercase, you can commit to the branch I think, or you can reopen this conversation

**Comment by SirEndii** [comment]
> > I'll look into your PRs in the next week if I get the time
> 
> Idk if you need I merge my prs and let you check easier? :)

What do you mean? I would review that later when I get the time

**Comment by zyxkad** [comment]
> > > I'll look into your PRs in the next week if I get the time
> > 
> > 
> > Idk if you need I merge my prs and let you check easier? :)
> 
> What do you mean? I would review that later when I get the time

I understand you don't have time now. It's ok.  
I mean I have 4 branchs for the PRs now, If you need to merge them?

File: src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java (hunk 1 above)
Comment (SirEndii) [reply src/main/java/de/srendi/advancedperipherals/common/util/CoordUtil.java]: Uhm, I didn't even see that

I mean the initialization of the var `side`

So instead of
```java
    public static Direction getDirection(FrontAndTop orientation, final String computerSide) throws LuaException {
        if (computerSide == null) {
            throw new LuaException("null is not a valid side");
        }

        final String side = computerSide.toLowerCase(Locale.ROOT);
```

You do
```java
    public static Direction getDirection(FrontAndTop orientation, String computerSide) throws LuaException {
        if (computerSide == null) {
            throw new LuaException("null is not a valid side");
        }

       computerSide = computerSide.toLowerCase(LocaleRoot);
```

And remove `side` completely which would remove one unnecessary var

**Comment by SirEndii** [comment]
> > > > I'll look into your PRs in the next week if I get the time
> > > 
> > > 
> > > Idk if you need I merge my prs and let you check easier? :)
> > 
> > 
> > What do you mean? I would review that later when I get the time
> 
> I understand you don't have time now. It's ok. I mean I have 4 branchs for the PRs now, If you need to merge them?

Nah that's okay

Splitting the PRs gives me a better overview

**Comment by SirEndii** [comment]
You forgot to replace all the `side` usages with `computerSide`

**Comment by zyxkad** [comment]
> You forgot to replace all the `side` usages with `computerSide`

Sry, forgot check :(

**Review by Patprehn — APPROVED** [review]

**Comment by Patprehn** [comment]
Thanks for all the contributions you made! ❤️  I'll merge them now and release a preview version for the testers. The preview will be available until Srendi releases the version to curseforge and modrinth
Check the releases in the next hours if you want to test the preview version yourself!

**Comment by zyxkad** [comment]
Wait, I didn't do anything about issue 436 anyway, why you thanks me at <https://github.com/SirEndii/AdvancedPeripherals/releases/tag/1.19.2-0.7.28r-Dev> :)

@Patprehn

**Comment by Patprehn** [comment]
Woops not sure how I messed that up
