### PR TITLE
Player rotate handle feature

### LINKED ISSUE #718: [0.8] Keyboard will not work after turtle moved
### Describe

Since keyboard binds itself to specific position, it won't work for moving turtles.

### Steps to reproduce

1. place a turtle
2. bind keyboard to the turtle
3. move the turtle
4. keyboard won't work on the turtle unless rebind its new position.

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.19.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by zyxkad**
**PLEASE READ THE [GUIDELINES](https://github.com/SirEndii/AdvancedPeripherals/blob/dev/1.20.1/CONTRIBUTING.md) BEFORE MAKING A CONTRIBUTION**

* **Please check if the PR fulfills these requirements**
- [x] The commit message are well described
- [ ] Docs have been added / updated (for features or maybe bugs which were noted). If not, please update the needed documentation [here](https://github.com/SirEndii/Advanced-Peripherals-Documentation/pulls). Feel free to remove this check if you don't need it
- [x] All changes have fully been tested

* **What kind of change does this PR introduce?** (Bug fix, feature, ...)
   Bug feature

* **What is the current behavior?** (You can also link to an open issue here)
   - #718

* **What is the new behavior (if this is a feature change)?**
   - IntelligenceModding/Advanced-Peripherals-Features#112

* **Does this PR introduce a breaking change?** (What changes might users need to make in their scripts due to this PR?)
   Kind of

* **Other information**:
   - add events:
      - `"keyboard_open"` fire when keyboard is actived
      - `"keyboard_closed"` fire when keyboard is deactived
      - `"player_mouse_move"`: `deltaX, deltaY`
      - `"player_mouse_click"`: `button`
      - `"player_mouse_up"`: `button`
      - `"player_mouse_scroll"`: `delta`
   - add API on keyboard upgrade:
      - `isCapturingMouse`: whether the mouse event is forwarded as CC events.
      - `setCaptureMouse`: set if the mouse event should be forwarded as CC events when keyboard is active.

### CODE REVIEW

File: src/main/java/de/srendi/advancedperipherals/common/items/KeyboardItem.java [hunk 1]
```diff
@@ -54,69 +56,86 @@ public boolean isEnabled() {
...
-                NetworkHooks.openScreen(serverPlayer, ((IInventoryItem) this).createContainer(serverPlayer, itemStack), buf -> {
-                    buf.writeBlockPos(serverPlayer.blockPosition());
-                    buf.writeItem(itemStack);
-                });
-            }
+        if (!(entity instanceof ServerPlayer serverPlayer)) {
+            return;
+        }
+        // TODO: this for sure won't work on dedicated server
+        if (!KeyBindings.GLASSES_HOTKEY_KEYBINDING.isDown()) {
```
Comment (zyxkad) [inline src/main/java/de/srendi/advancedperipherals/common/items/KeyboardItem.java:104]: Just note this need some investigate for dedicated server.

**Review by SirEndii — APPROVED** [review]
LGTM
