### PR TITLE
ensure the redstone output value is between [0,15]

### LINKED ISSUE #611: [Redstone Integrator] setAnalogOutput and getAnalogOutput can exceed maximum value
### Describe

When using the Redstone Integrator, a analog output power greater than the redstone maximum of 15 can be set and retrieved.

### Steps to reproduce

1. Place a Computer and a Redstone integrator
2. In the Lua console:
```
lua> p = peripheral.find("redstoneIntegrator")
lua> p.setAnalogOutput("back", 200)
lua> p.getAnalogOutput("back")
200
```
3. The analog output is not clamped to the redstone maximum of 15

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.3.13 / Minecraft 1.19.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by zyxkad**
**PLEASE READ THE [GUIDELINES](https://github.com/SirEndii/AdvancedPeripherals/blob/dev/1.20.1/CONTRIBUTING.md) BEFORE MAKING A CONTRIBUTION**

* **Please check if the PR fulfills these requirements**
- [x] The commit message are well described
- [x] All changes have fully been tested

* **What kind of change does this PR introduce?** (Bug fix, feature, ...)
  Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
  - #611

* **Does this PR introduce a breaking change?** (What changes might users need to make in their scripts due to this PR?)
  N/A

### CODE REVIEW

File: src/main/java/de/srendi/advancedperipherals/common/blocks/blockentities/RedstoneIntegratorEntity.java [hunk 1]
```diff
@@ -82,6 +82,11 @@ private void updateRedstoneOutputs() {
      * @param power     The redstone power from 0 to 15
      */
     public void setOutput(Direction direction, int power) {
+        if (power > 15) {
+            power = 15;
+        } else if (power < 0) {
+            power = 0;
+        }
```
Comment (SirEndii) [inline src/main/java/de/srendi/advancedperipherals/common/blocks/blockentities/RedstoneIntegratorEntity.java]: What do you think about

```suggestion
        power = Math.min(Math.max(power, 0), 15);
```

**Review by SirEndii — APPROVED** [review]
