### PR TITLE
AdvancedPeripheral Blocks now keep their name when changed after placing and/or destroying

### LINKED ISSUE #629: Placed blocks do not retain their custom block name when destroyed
### Describe

Title says it all. Right now it's not a huge issue in my world because I usually place the blocks then never move them.

It would be SUPER handy if blocks retained their names, especially so in complex system in order to identify them easily without a very involved custom configuration step.

### Steps to reproduce

1) Rename a block from the mod in an anvil and place it down somewhere.
2) Hook up a wired modem and call `getName()` on the block. You'll see the new name.
3) If using Jade (block info mod), the block's new name is never shown, only its original name.
4) Breaking the block reverts it back to its original name.

### Multiplayer?

No

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.20.1

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by WiggleWizard**
* **Please check if the PR fulfills these requirements**
- [x] The commit message are well described
- [ ] Docs have been added / updated (for features or maybe bugs which were noted). If not, please update the needed documentation [here](https://github.com/SirEndii/Advanced-Peripherals-Documentation/pulls). This is not mandatory
- [x] All changes have fully been tested

* **What kind of change does this PR introduce?** (Bug fix, feature, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/IntelligenceModding/AdvancedPeripherals/issues/629

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their scripts due to this PR?)
No

* **Other information**:

### CODE REVIEW

File: src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/owner/BlockEntityPeripheralOwner.java [hunk 1]
```diff
@@ -32,7 +33,14 @@ public BlockEntityPeripheralOwner(T tileEntity) {
     @Nullable
     @Override
     public String getCustomName() {
-        return tileEntity.getPersistentData().getString("CustomName");
+        String result = "";
+        
+        if (tileEntity instanceof Nameable nameableEntity)
+        {
```
Comment (zyxkad) [inline src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/owner/BlockEntityPeripheralOwner.java]:
```suggestion
        if (tileEntity instanceof Nameable nameableEntity) {
```

File: src/main/java/de/srendi/advancedperipherals/common/blocks/base/BaseBlockEntityBlock.java [hunk 2]
```diff
@@ -64,7 +65,10 @@ public void setPlacedBy(@NotNull Level worldIn, @NotNull BlockPos pos, @NotNull
         if (worldIn.getBlockEntity(pos) == null)
             return;
         //Used for the lua function getName()
-        worldIn.getBlockEntity(pos).getPersistentData().putString("CustomName", stack.getDisplayName().getString());
+        BlockEntity blockEntity;
+        if (stack.hasCustomHoverName() && (blockEntity = worldIn.getBlockEntity(pos)) instanceof BaseContainerBlockEntity) {
+            ((BaseContainerBlockEntity)blockEntity).setCustomName(stack.getHoverName());
```
Comment (zyxkad) [inline src/main/java/de/srendi/advancedperipherals/common/blocks/base/BaseBlockEntityBlock.java]:
```suggestion
        if (stack.hasCustomHoverName() && worldIn.getBlockEntity(pos) instanceof BaseContainerBlockEntity blockEntity) {
            blockEntity.setCustomName(stack.getHoverName());
```

File: src/main/java/de/srendi/advancedperipherals/common/data/BlockLootTables.java [hunk 3]
```diff
@@ -17,7 +17,10 @@ protected BlockLootTables() {
 
     @Override
     protected void generate() {
-        Registration.BLOCKS.getEntries().stream().map(RegistryObject::get).forEach(this::dropSelf);
+        Registration.BLOCKS.getEntries().stream().map(RegistryObject::get).forEach(registeredBlock -> {
+            //Allow blocks to transfer their name to the dropped block when broken
+            this.add(registeredBlock, (Block block) -> this.createNameableBlockEntityTable((Block)block));
```
Comment (zyxkad) [inline src/main/java/de/srendi/advancedperipherals/common/data/BlockLootTables.java]:
```suggestion
            this.add(registeredBlock, (block) -> this.createNameableBlockEntityTable(block));
```

**Review by zyxkad — CHANGES_REQUESTED** [review]
Need fix some style

**Comment by zyxkad** [comment]
Can you to create a PR for 1.19.2? Because https://github.com/IntelligenceModding/AdvancedPeripherals/blob/dev/1.20.1/CONTRIBUTING.md#setting-up-a-development-environment

> PLEASE READ If you want to add features or fix bugs that exist in multiple versions, please make the changes for the oldest fully supported versions, which you can find [here](https://docs.advanced-peripherals.de/#version-support). That would be 1.19.2 at the time the article was written.

**Review by zyxkad — APPROVED** [review]
